import File from "../assets/file-storage.svg";
import Flight from "../assets/flights.svg";
import Sound from "../assets/megaphone.svg";

const DATA = {
  availableBalance: 12650,
  cards: [
    {
      cardNumber: '4312 8765 2301 7890',
      expiry: '07/27',
      cvv: '774',
      isFreeze:false,
      isShow:false,
      cardDetails: {
        name: 'Arpit Anand',
        dob: '12 Jul 1995',
        pan: 'ARPTA1234K',
      },
      transaction: [
        {
          title: 'Amazon',
          date: '15 May 2025',
          amount: '1,250',
          type: 'CREDIT',
          icon: 'file',
          color: '#009DFF1A',
          iconComp: File,
        },
        {
          title: 'IndiGo Airlines',
          date: '12 May 2025',
          amount: '6,300',
          type: 'DEBIT',
          icon: 'flight',
          color: '#00D6B51A',
          iconComp: Flight,
        },
        {
          title: 'Spotify Premium',
          date: '10 May 2025',
          amount: '199',
          type: 'DEBIT',
          icon: 'sound',
          color: '#F251951A',
          iconComp: Sound,
        },
        {
          title: 'Google Drive',
          date: '08 May 2025',
          amount: '650',
          type: 'DEBIT',
          icon: 'file',
          color: '#009DFF1A',
          iconComp: File,
        },
      ],
    },
    {
      cardNumber: '5599 0023 1144 6781',
      expiry: '03/26',
      cvv: '902',
      isFreeze:true,
      isShow:false,
      cardDetails: {
        name: 'Suresh Raina',
        dob: '22 Sep 1993',
        pan: 'RAJAN5678T',
      },
      transaction: [
        {
          title: 'Flipkart',
          date: '18 Apr 2025',
          amount: '2,499',
          type: 'CREDIT',
          icon: 'file',
          color: '#009DFF1A',
          iconComp: File,
        },
        {
          title: 'Vistara Flight',
          date: '14 Apr 2025',
          amount: '5,800',
          type: 'DEBIT',
          icon: 'flight',
          color: '#00D6B51A',
          iconComp: Flight,
        },
        {
          title: 'Apple Music',
          date: '13 Apr 2025',
          amount: '99',
          type: 'DEBIT',
          icon: 'sound',
          color: '#F251951A',
          iconComp: Sound,
        },
        {
          title: 'Dropbox',
          date: '11 Apr 2025',
          amount: '900',
          type: 'DEBIT',
          icon: 'file',
          color: '#009DFF1A',
          iconComp: File,
        },
      ],
    },
    {
      cardNumber: '6012 7890 4432 1233',
      expiry: '11/25',
      cvv: '456',
      isFreeze:false,
      isShow:false,
      cardDetails: {
        name: 'Kasish Mehta',
        dob: '05 Mar 1992',
        pan: 'SNHME1234Z',
      },
      transaction: [
        {
          title: 'Zara',
          date: '28 Mar 2025',
          amount: '3,200',
          type: 'CREDIT',
          icon: 'file',
          color: '#009DFF1A',
          iconComp: File,
        },
        {
          title: 'GoAir',
          date: '25 Mar 2025',
          amount: '4,990',
          type: 'DEBIT',
          icon: 'flight',
          color: '#00D6B51A',
          iconComp: Flight,
        },
        {
          title: 'Audible',
          date: '24 Mar 2025',
          amount: '149',
          type: 'DEBIT',
          icon: 'sound',
          color: '#F251951A',
          iconComp: Sound,
        },
        {
          title: 'WeTransfer Pro',
          date: '22 Mar 2025',
          amount: '499',
          type: 'DEBIT',
          icon: 'file',
          color: '#009DFF1A',
          iconComp: File,
        },
      ],
    },
  ],
};

export default DATA;
